# Copyright 2024 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

declare_args() {
  # On-device translation and the web Translation API are excluded by default.
  enable_on_device_translation = false
}
